# Generated by Django 5.1 on 2024-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('last_7_day_sale', models.FloatField()),
                ('fit', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('neck', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
